### ISSUE TITLE
Does not have libary for the current platform (PCRE)

### ISSUE THREAD

**Issue by zwrawr** [godotengine/godot-git-plugin#82] opened 2021-10-02 19:24 UTC
OS: Ubuntu 20.04 LTS

```
Unable to load addon script from path: 'res://addons/godot-git-plugin-v1.2.2/godot-git-plugin/git_api.gdns'. This might be due to a code error in that script.
Disabling the addon at 'res://addons/godot-git-plugin-v1.2.2/godot-git-plugin/plugin.cfg' to prevent further errors.
```

```
 GDScript language server started ---
  does not have a library for the current platform.
 Failed to get modified time for: res://addons/godot-git-plugin/git_api.gdnlib.
  does not have a library for the current platform.
 core/project_settings.cpp:209 - Property not found: editor_plugins/enabled
```

**Comment by ChronicallySerious** [comment] 2021-10-02 20:02
The error is probably because of the contents of the release .zip file being present one level deeper than they need to be.

In your case, try just copying `res://addons/godot-git-plugin-v1.2.2/godot-git-plugin` to `res://addons/godot-git-plugin` and then you can delete `res://addons/godot-git-plugin-v1.2.2`.

**Comment by ChronicallySerious** [comment] 2021-10-02 20:08
Just added a note of this in the wiki

**Comment by ChronicallySerious** [comment] 2021-10-02 20:15
Could you confirm that you have downloaded the plugin through the Asset Library?

**Comment by zwrawr** [comment] 2021-10-04 18:15
I wasn't installing from the Asset Library but from the GitHub releases. When I install the Asset library version I get this error.
```
Godot Engine v3.3.4.stable.mono.official (c) 2007-2021 Juan Linietsky, Ariel Manzur & Godot Contributors.
--- GDScript language server started ---
 Can't open dynamic library: /mnt/slowssd/Repos/godot/LD49/addons/godot-git-plugin/x11/release/libgitapi.so. Error: /mnt/slowssd/Repos/godot/LD49/addons/godot-git-plugin/x11/release/libgitapi.so: undefined symbol: pcre_free
 modules/gdnative/gdnative.cpp:502 - No valid library handle, can't get symbol from GDNative object
 modules/gdnative/nativescript/nativescript.cpp:1482 - No nativescript_init in "res://addons/godot-git-plugin/x11/release/libgitapi.so" found
```

**Comment by ChronicallySerious** [comment] 2021-10-04 18:53
@zwrawr That looks like the same issue as https://github.com/godotengine/godot-git-plugin/issues/83

**Comment by zwrawr** [comment] 2021-10-04 19:36
Looks like I already have it installed
```bash
sudo apt-get install libpcre3
...
libpcre3 is already the newest version (2:8.39-12build1).
```

**Comment by ChronicallySerious** [comment] 2021-10-04 19:41
Thanks for confirming. I am marking this as a bug. The fix should be simple because this is now identified as a regression due to missing an option in our compilation flags.

**Comment by eeclarkjr** [comment] 2021-12-12 16:38
Zip file downloaded and saved into addons folder (path shown below)
Get the follow error when trying to enable.

_Unable to load addon script from path: 'res://addons/godot-git-plugin/git_api.gdns' There seems to be an error in the code, please check the syntax._

**Comment by ChronicallySerious** [comment] 2021-12-12 17:31
@eeclarkjr Any chance you are using the mono build of Godot?

**Comment by PixsaOJ** [comment] 2021-12-16 08:37
Godot 3.4 came up.

I used to fall back to version 1.2.1, and it worked, but now that's not even an option. So I can't really use this plugin anymore. Hopefully will be fixed soon. If you need any debugging or assistance from me, I am glad to help. I am starting new project and don't want to use other GitHub plugin (I use GitLab).

**Comment by ChronicallySerious** [comment] 2021-12-25 10:49
@PixsaOJ Godot 3.4 should be working with v1.2.1. The behaviour you see that the VCS needs to be initialized every time you open the project in Godot is actually the correct behaviour from this plugin and has been the behaviour in all v1.x.

However, we have built a way to fix that in the upcoming v2 with https://github.com/godotengine/godot/pull/53900 and #84 along with new features including network-related ones.

**Comment by ChronicallySerious** [comment] 2022-01-14 18:10
The Godot 3.5 beta1 is now live. And along with it, we released a v2.0.0 of this plugin which should fix this issue.

**Closed by ChronicallySerious** 2022-01-14 18:10 UTC
Labels: bug

**Comment by ChronicallySerious** [comment] 2022-02-01 14:12
While v2.x fixes this issue, the fix was backported to v1.x as well. The new v1.2.3 should not show any PCRE undefined symbol errors.

**Comment by fenamori** [comment] 2023-01-09 23:16
I'm getting the same error as #90 on Godot v3.5.1.stable running EndeavourOS (Linux kernel 6.1.4-arch1-1).

```
Can't open dynamic library: /(project path)/addons/godot-git-plugin/linux/libgitapi.so. Error: /(project path)/addons/godot-git-plugin/linux/libgitapi.so: failed to map segment from shared object
 
modules/gdnative/gdnative.cpp:510 - No valid library handle, can't get symbol from GDNative object
 
modules/gdnative/nativescript/nativescript.cpp:1503 - No nativescript_init in "res://addons/godot-git-plugin/linux/libgitapi.so" found
```
 
 
![image](https://user-images.githubusercontent.com/44845481/211427091-fc35405f-ae15-4224-9a97-12c926cbed4b.png)

**Comment by View-my-Git-Lab-krafi** [comment] 2023-11-04 13:19
https://github.com/touilleMan/godot-python/issues/396

**Comment by Calinou** [comment] 2023-11-05 23:21
@View-my-Git-Lab-krafi This issue is unrelated to the Godot Git plugin.
