### ISSUE TITLE
LFS Support?

### ISSUE THREAD

**Issue by heroofhyla** [godotengine/godot-git-plugin#57] opened 2021-02-04 21:52 UTC
I've been using this plugin along with git-lfs (large file storage) on my current project, and I've just discovered that they don't seem to be behaving together properly. If I commit a file that should be tracked with LFS using the plugin, it doesn't actually get handled by LFS, it's just treated as a regular file. The problem isn't apparent until either a push (where I notice that I don't see any `Uploading LFS objects` line) or a checkout, where I get an error like this:

```
Encountered 7 file(s) that should have been pointers, but weren't:
```

LFS works fine if I just handle my commits and pushes from git-bash instead of using the plugin.

Is support for LFS coming at some point? Or am I perhaps doing something wrong?

**Comment by IronicallySerious** [comment] 2021-02-04 23:42
My experience with Git LFS is a bit short but based on what I have read so far on Git LFS and libgit2, LFS is not supported by godot-git-plugin as of now, however, it is possible to add it because our Git backend i.e. libgit2, allows us to introduce 'filters'. 

LFS [seems to work by](https://www.atlassian.com/git/tutorials/git-lfs) introducing a concept of file pointers into the process of committing a large file. Since Git LFS abstracts this away from the user as a Git extension, we don't see the pointers directly exposed in our common workflow of `git add > git commit > git push`.

ligbit2 does NOT have a Git LFS filter implementation built into it, however, it has filter implementations which perform other tasks (like CRLF and indentations conversions), but I see that [it is claimed](https://github.com/libgit2/libgit2/issues/1473) that Git LFS support can be "plugged in" by registering a custom filter into libgit2 which performs the smudge and clean operations by calling external programs (via CLI most probably?) like `git lfs` whenever needed.

So our task will probably be to create a filter in case Git LFS has been installed and in use, and call into Git LFS from that filter whenever libgit2 signals us through that filter.

We had not planned the LFS support as of now. However, there is nothing stopping me or whoever who'd want to help from doing it now :). I will likely discuss this with the other devs on the contributor chat and report back.

**Comment by IronicallySerious** [comment] 2021-02-05 09:26
Based on some discussion, we came to the conclusion that this would be a rarely used feature if implemented. We also have other more urgent features to merge/polish with the upcoming v2.0 so this specific feature is low on the priority list as of now.

Closing the issue since we possibly will not work on it right away, however when the other features get implemented and the demand for this one rises, we will definitely consider this again.

**Closed by IronicallySerious** 2021-02-05 09:26 UTC
Labels: enhancement

**Comment by christopwner** [comment] 2021-04-24 02:06
this would be a nice to have for high-res textures or 3d models

**Comment by NangiDev** [comment] 2023-04-05 07:42
Since GitHub now added their file size limit this has become a bit more urgent I think.

**Comment by GlaireDaggers** [comment] 2026-05-03 19:42
I've been looking into what would be involved in implementing this, since for serious game development I would frankly consider LFS support to be a must-have.

I can see how to implement a custom filter - something to the effect of:
```
git_filter *filter = new git_filter();
filter->version = GIT_FILTER_VERSION;
filter->attributes = "filter=lfs";
filter->initialize = _lfs_filter_initialize;
filter->shutdown = _lfs_filter_shutdown;
filter->check = _lfs_filter_check;
filter->apply = nullptr;
filter->stream = _lfs_filter_stream;
filter->cleanup = _lfs_filter_cleanup;

git_filter_register("lfs", filter, 200);
```

Now, the overall flow here would be that for a given file, `filter->stream` is called given a `next` stream it needs to write to, and it allocates a `git_writestream` object - that object has a write callback which would do the processing necessary & write results to the aforementioned `next` stream. Then once everything has been written to that stream, `filter->cleanup` would be called.

The easiest way I can see of doing this would be to just shell out to `git lfs clean` and `git lfs smudge` (which one can be determined by checking the mode field of the `git_filter_source` passed to the stream function). The writestream object it allocates would take all of the bytes written to it via the write callback and then pipe them into the stdin of the LFS command, and in turn take the stdout of that same command and write it to the `next` stream.

This could be accomplished via `OS.execute_with_pipe` but that would raise the minimum Godot version to 4.3

(the other option is implementing the LFS protocol instead of shelling out, which would be significantly more work)

**Comment by Calinou** [comment] 2026-05-04 00:05
> This could be accomplished via `OS.execute_with_pipe` but that would raise the minimum Godot version to 4.3

I consider this reasonable, since [4.5 is the oldest supported version as of writing](https://docs.godotengine.org/en/latest/about/release_policy.html#release-support-timeline).

**Comment by GlaireDaggers** [comment] 2026-05-04 01:34
Good to know, although after doing some experimentation there's unfortunately a critical limitation here with `OS.execute_with_pipe`. The problem is that `git lfs clean` and `git lfs smudge` are both expecting you to write to the stdin and then close it to indicate when all data has been sent. It won't write any output to stdout until that happens.

Unfortunately, `OS.execute_with_pipe` combines stdin and stdout into one single `FileAccess` object. As far as I can tell, I can't close the stdin without also closing stdout and thus being unable to read the output of the command.

**Comment by twaritwaikar** [comment] 2026-05-04 13:12
I am not sure of the normal norms of building modules nowadays but it should be fine to just use the C++ std library utils for executing shell commands. 

Also, I do want to point out a very interesting turn here. We intentionally used libgit2 here to avoid making shell calls to the Git CLI, and thus avoiding having to parse Git's wonky output format. 

Shelling out to Git LFS is easy but if we are doing that, we might as well throw all of the libgit2 code out the window (unironically) for ease of installation and development on this plugin

(libgit2, with all it's due merits, has been a huge PITA to work with in my journey starting from this project and well into my dayjob)

**Comment by GlaireDaggers** [comment] 2026-05-04 18:22
> I am not sure of the normal norms of building modules nowadays but it should be fine to just use the C++ std library utils for executing shell commands.

True, though I'd have to use POSIX calls like `pipe()` to do this since I'm pretty sure that's not covered by std so there'd have to be some OS-specific ifdefs to handle that most likely (which I was hoping to avoid by taking advantage of Godot's existing functionality)

> Shelling out to Git LFS is easy but if we are doing that, we might as well throw all of the libgit2 code out the window (unironically) for ease of installation and development on this plugin

That _would_ pretty much eliminate all issues wrt filters (would not only support LFS but any other arbitrary filters too), though yeah parsing output is its own can of worms (lots of user-facing commands do not have a stable documented output format - though some do, like `git status -s` or `git diff --cc`). One upside of doing it that way is that it can be done with regular old `OS.execute` calls without bumping the minimum Godot version at all - just provide the parameters & then read the return code & output.

(though maybe worth noting with git lfs clean & smudge is that there's nothing to parse - you just shove some file bytes into stdin and get some file bytes out of stdout)
