### ISSUE TITLE
Update plugin for Godot 4.2 due to GDExtension compatibility breakage

### ISSUE THREAD

**Issue by Dorro101** [godotengine/godot-git-plugin#196] opened 2023-07-07 03:16 UTC
___

***Bugsquad note:** This issue has been confirmed several times already. No need to confirm it further.*

___

Hi

Followed the installation instructions provided by  the V3 wiki. Drag and dropped the extracted folder into my new project and...

![Screenshot from 2023-07-07 11-01-02](https://github.com/godotengine/godot-git-plugin/assets/54166678/9bfaddc1-1955-48c6-9370-9640c34920c1)

I have just started trying out Godot, but have used git and have a Github account I use for my OpenSCAD projects, which I edit using VS Codium on Fedora Linux 38 (Workstation Edition) on my Lenovo ThinkPad X1 Tablet Gen 3 without issues.

Do I have to wait for a new release, as my casual scanning of the release docs leads me to believe that changes have been made to the GDExtension code?

Thanks
Dorian

**Comment by cyanindya** [comment] 2023-07-07 03:26
I hope it's okay for me to add a bit of info into your issue.

I just updated to Godot 4.1, and I ran into the same issue. The output pane also printed the following error messages:
![image](https://github.com/godotengine/godot-git-plugin/assets/19756942/6bbb10d3-0dcc-4f92-a2ff-f383d8bfdd29)

**Comment by Dorro101** [comment] 2023-07-07 03:45
Cool, thanks. Did not think to include the console output. I had to hunt around a bit for a download for the previous version of Godot (4.0.3) and it seems to be working in that version. As said, just started like in today. Maybe a bit back to front, but my OCD wants my backups in place before I start any new project. I will reign it in a bit (the OCD) and get to grips with the engine first and the worry about version control later.

**Comment by scorpion182** [comment] 2023-07-07 03:48
i am facing the same issue too
![image](https://github.com/godotengine/godot-git-plugin/assets/19986771/4dbf85fe-d01e-448c-b78f-60038b8129bb)

**Comment by Eisendroid** [comment] 2023-07-07 07:29
Same issue on Linux. Added the "compatiblity_minimum" line in the git_plugin.gdextension file:

![Bildschirmfoto vom 2023-07-07 09-26-36](https://github.com/godotengine/godot-git-plugin/assets/72012005/e2284c3f-1ccf-40fa-bfb5-ebcb1bfda186)

The error message slightly changes, still does not work:

![Bildschirmfoto vom 2023-07-07 09-26-59](https://github.com/godotengine/godot-git-plugin/assets/72012005/03fa66dd-0172-4422-bb83-53bfc303b36a)

**Comment by BoydyBoydy** [comment] 2023-07-07 12:17
I also get this error. Same output as @Dorro101 
Get tried to convert over to 4.1 and it wouldn't load.

I can still use GIT via command line...

**Comment by AFCMS** [comment] 2023-07-07 19:44
Guess its because of this....

https://github.com/godotengine/godot-docs/pull/7611/commits/51f7e5c4faec3eee80f21afc47e84a466dcccb7b#diff-0d2c3bbaf7abd047105aefccd9684c367fe5edace2f44ed181bf2636ba53fab0R16-R18

**Comment by rgreening** [comment] 2023-07-08 15:59
So, the current git plugin is only 4.0 compatible and will need an update to recompile for 4.1? If i understood the last post correctly. Maybe? My project is stalled atm because we need 4.1 and git at same time. ;)

**Comment by Zylann** [comment] 2023-07-08 16:01
Note, you can still use Git without a plugin, it might just be less convenient tho

**Comment by rgreening** [comment] 2023-07-08 17:03
> Note, you can still use Git without a plugin in the meantime, it might just be less convenient tho

I do use it on CLI to push/pull from github but the realtime updates when you accodentally modify a file dont show up and when making a lot of changes its better in the UI to spot those as soon as they happen. I have made a few good catches that i would have missed easily if only committing via cli.

**Comment by rgreening** [comment] 2023-07-08 17:04
As it stands i had to revert to godot 4.0 to continue my project. Any plan rebuild against 4.1 which is what appears to be required to fix the issue at a minimum...

**Comment by Calinou** [comment] 2023-07-09 14:50
cc @twaritwaikar

**Comment by WiseNoodle** [comment] 2023-07-10 01:45
Can confirm, same issues on Windows 10 and Mac. Hope this can be resolved soon!

**Comment by NASATA777** [comment] 2023-07-24 12:26
I also get this error. From v4.1.1.
![error](https://github.com/godotengine/godot-git-plugin/assets/63277090/103c3b8a-6c08-4829-a170-194e3dacf8be)

**Comment by AdaLollA** [comment] 2023-07-25 14:20
Would really love to see the update go through. Some people are already reporting that the pull request above is working for them.

**Comment by Calinou** [comment] 2023-07-25 15:12
@AdaLollA Please don't bump issues without contributing significant new information. Use the :+1: reaction button on the first post instead.

**Comment by daveTheOldCoder** [comment] 2023-08-27 17:47
Can you explain the process of updating this plugin for 4.1+? Does it require deep knowledge of  GDExtension?

**Comment by paddy-exe** [comment] 2023-09-06 22:31
Hey everyone, I updated the extension for 4.1 and tested it successfully on Windows. If anyone of you is on Linux, I'd appreciate if you could test the PR: https://github.com/godotengine/godot-git-plugin/pull/203

**Comment by daveTheOldCoder** [comment] 2023-09-07 03:18
Are these instructions still correct for testing  this PR?
https://github.com/godotengine/godot-git-plugin/blob/6a6f7d1810352ecf6f5153300ea9fa5a3341dfe2/README.md?plain=1

**Comment by pancelor** [comment] 2023-09-07 04:20
I installed it through the asset store, restarted my project (and got the expected error), restarted again but still got errors: (in the output tab)
> core/extension/gdextension.cpp:593 - GDExtension configuration file must contain a "configuration/compatibility_minimum" key: res://addons/godot-git-plugin/git_plugin.gdextension
> Failed loading resource: res://addons/godot-git-plugin/git_plugin.gdextension. Make sure resources have been imported by opening the project in the editor at least once.

I added `compatibility_minimum = 4.1` based on the [docs](https://docs.godotengine.org/en/stable/tutorials/migrating/upgrading_to_godot_4.1.html#updating-your-gdextension-for-4-1) and now the project won't load -- godot crashes as soon as I try to open that project. I'm not sure if there's some better info I can give than this, but here's a stacktrace from `coredumpctl debug godot`. I'm running Manjaro and `godot --version` tells me `4.1.stable.arch_linux`

```
Stack trace of thread 7696:
                #0  0x00007fc74032526c n/a (libc.so.6 + 0x8926c)
                #1  0x00007fc7402d5a08 raise (libc.so.6 + 0x39a08)
                #2  0x00007fc7402be538 abort (libc.so.6 + 0x22538)
                #3  0x00005573c465f8b7 n/a (godot + 0x11d68b7)
                #4  0x00007fc7402d5ab0 n/a (libc.so.6 + 0x39ab0)
                #5  0x00007fc73861551e _ZN5godot7Variant13init_bindingsEv (libgit_plugin.linux.editor.x86_64.so + 0x21551e)
                #6  0x00007fc73860b465 _ZN5godot18GDExtensionBinding4initEPK20GDExtensionInterfacePvP25GDExtensionInitialization (libgit_plugin.linux.editor.x86_64.so + 0x20b465)
                #7  0x00007fc73850e7c9 git_plugin_init (libgit_plugin.linux.editor.x86_64.so + 0x10e7c9)
                #8  0x00005573c804a5dc n/a (godot + 0x4bc15dc)
                #9  0x00005573c80af8fe n/a (godot + 0x4c268fe)
                #10 0x00005573c7da90ba n/a (godot + 0x49200ba)
                #11 0x00005573c7db0513 n/a (godot + 0x4927513)
                #12 0x00005573c7df62a1 n/a (godot + 0x496d2a1)
                #13 0x00005573c7df7162 n/a (godot + 0x496e162)
                #14 0x00005573c804868c n/a (godot + 0x4bbf68c)
                #15 0x00005573c80643e4 n/a (godot + 0x4bdb3e4)
                #16 0x00005573c838816c n/a (godot + 0x4eff16c)
                #17 0x00005573c45fdea7 n/a (godot + 0x1174ea7)
                #18 0x00007fc7402bf850 n/a (libc.so.6 + 0x23850)
                #19 0x00007fc7402bf90a __libc_start_main (libc.so.6 + 0x2390a)
                #20 0x00005573c460ca55 n/a (godot + 0x1183a55)
```

**Comment by paddy-exe** [comment] 2023-09-07 08:11
> Are these instructions still correct for testing  this PR?
> 
> https://github.com/godotengine/godot-git-plugin/blob/6a6f7d1810352ecf6f5153300ea9fa5a3341dfe2/README.md?plain=1
> 
> 
> 
> That's the same as the file that's in the .zip download for this PR.

No, it is not. The latest release is for 4.0 currently and since then the dev builds have changed as well. You can have a look at the GDExtension docs for the 4.1 version (be sure to check which docs branch you read)

**Comment by paddy-exe** [comment] 2023-09-07 08:12
> I installed it through the asset store, restarted my project (and got the expected error), restarted again but still got errors: (in the output tab)
> 
> > core/extension/gdextension.cpp:593 - GDExtension configuration file must contain a "configuration/compatibility_minimum" key: res://addons/godot-git-plugin/git_plugin.gdextension
> 
> > Failed loading resource: res://addons/godot-git-plugin/git_plugin.gdextension. Make sure resources have been imported by opening the project in the editor at least once.
> 
> 
> 
> I added `compatibility_minimum = 4.1` based on the [docs](https://docs.godotengine.org/en/stable/tutorials/migrating/upgrading_to_godot_4.1.html#updating-your-gdextension-for-4-1) and now the project won't load -- godot crashes as soon as I try to open that project. I'm not sure if there's some better info I can give than this, but here's a stacktrace from `coredumpctl debug godot`. I'm running Manjaro and `godot --version` tells me `4.1.stable.arch_linux`
> 
> 
> 
> ```
> 
> Stack trace of thread 7696:
> 
>                 #0  0x00007fc74032526c n/a (libc.so.6 + 0x8926c)
> 
>                 #1  0x00007fc7402d5a08 raise (libc.so.6 + 0x39a08)
> 
>                 #2  0x00007fc7402be538 abort (libc.so.6 + 0x22538)
> 
>                 #3  0x00005573c465f8b7 n/a (godot + 0x11d68b7)
> 
>                 #4  0x00007fc7402d5ab0 n/a (libc.so.6 + 0x39ab0)
> 
>                 #5  0x00007fc73861551e _ZN5godot7Variant13init_bindingsEv (libgit_plugin.linux.editor.x86_64.so + 0x21551e)
> 
>                 #6  0x00007fc73860b465 _ZN5godot18GDExtensionBinding4initEPK20GDExtensionInterfacePvP25GDExtensionInitialization (libgit_plugin.linux.editor.x86_64.so + 0x20b465)
> 
>                 #7  0x00007fc73850e7c9 git_plugin_init (libgit_plugin.linux.editor.x86_64.so + 0x10e7c9)
> 
>                 #8  0x00005573c804a5dc n/a (godot + 0x4bc15dc)
> 
>                 #9  0x00005573c80af8fe n/a (godot + 0x4c268fe)
> 
>                 #10 0x00005573c7da90ba n/a (godot + 0x49200ba)
> 
>                 #11 0x00005573c7db0513 n/a (godot + 0x4927513)
> 
>                 #12 0x00005573c7df62a1 n/a (godot + 0x496d2a1)
> 
>                 #13 0x00005573c7df7162 n/a (godot + 0x496e162)
> 
>                 #14 0x00005573c804868c n/a (godot + 0x4bbf68c)
> 
>                 #15 0x00005573c80643e4 n/a (godot + 0x4bdb3e4)
> 
>                 #16 0x00005573c838816c n/a (godot + 0x4eff16c)
> 
>                 #17 0x00005573c45fdea7 n/a (godot + 0x1174ea7)
> 
>                 #18 0x00007fc7402bf850 n/a (libc.so.6 + 0x23850)
> 
>                 #19 0x00007fc7402bf90a __libc_start_main (libc.so.6 + 0x2390a)
> 
>                 #20 0x00005573c460ca55 n/a (godot + 0x1183a55)
> 
> ```
> 
> 
> 
> 

That is not the only thing you have to change to port the project to 4.1

**Comment by daveTheOldCoder** [comment] 2023-09-07 16:48
[quote]No, it is not. The latest release is for 4.0 currently and since then the dev builds have changed as well. You can have a look at the GDExtension docs for the 4.1 version (be sure to check which docs branch you read)[/quote]

I would like to help by testing this PR on Linux, but that's making my head explode. I humbly request that you update the readme. :)

**Comment by willowitzy** [comment] 2023-09-21 02:58
Can we have this by October?

**Comment by lel-amri** [comment] 2023-09-25 12:02
Admittedly fixed by https://github.com/godotengine/godot-git-plugin/pull/198

@willowitzy See [here](https://github.com/godotengine/godot-git-plugin/pull/198#pullrequestreview-1640554714) for a temporary version compatible with current stable.

**Comment by Calinou** [comment] 2023-09-27 21:17
Note that a tagged release with this commit included still needs to be made, so that official downloads support Godot 4.1 and later. In the meantime, you can download the current stable release and replace the native library with this PR's artifacts, which I've reuploaded for future reference:

- **Windows:** [libgit_plugin.windows.x86_64.editor.dll-c89b1f54a62707d96143ee336a3e0ee6b8ccb40e.zip](https://github.com/godotengine/godot-git-plugin/files/12704189/libgit_plugin.windows.x86_64.editor.dll-c89b1f54a62707d96143ee336a3e0ee6b8ccb40e.zip)
- **macOS:** [libgit_plugin.macos.universal.editor.dylib-c89b1f54a62707d96143ee336a3e0ee6b8ccb40e.zip](https://github.com/godotengine/godot-git-plugin/files/12704188/libgit_plugin.macos.universal.editor.dylib-c89b1f54a62707d96143ee336a3e0ee6b8ccb40e.zip)
- **Linux:** [libgit_plugin.linux.x86_64.editor.so-c89b1f54a62707d96143ee336a3e0ee6b8ccb40e.zip](https://github.com/godotengine/godot-git-plugin/files/12704187/libgit_plugin.linux.x86_64.editor.so-c89b1f54a62707d96143ee336a3e0ee6b8ccb40e.zip)

**Comment by CancerQ** [comment] 2023-10-24 05:49
@Calinou The current version 4.1 is not able to use GDExtension, using the macos ide, the import of GDExtension configuration file error

**Comment by CancerQ** [comment] 2023-10-24 05:50
> @Calinou The current version 4.1 is not able to use GDExtension, using the macos ide, the import of GDExtension configuration file error

Can only downgrade to 4.0？

**Comment by Calinou** [comment] 2023-10-25 02:20
> @Calinou The current version 4.1 is not able to use GDExtension, using the macos ide, the import of GDExtension configuration file error

GDExtension *is* available in 4.1, just like in 4.0. You need to use the extensions I linked rather than the ones on the Releases tab though.

**Comment by CancerQ** [comment] 2023-10-25 06:11
> > @Calinou The current version 4.1 is not able to use GDExtension, using the macos ide, the import of GDExtension configuration file error
> 
> GDExtension _is_ available in 4.1, just like in 4.0. You need to use the extensions I linked rather than the ones on the Releases tab though.

How do I compile my own GDExtension? I can't use it at the moment, it will report the error

**Comment by SonarBeserk** [comment] 2023-11-11 06:04
@Calinou Is there an outstanding issue preventing a patch release of the plugin? Based on the compare a handful of other bugs appear to have been resolved https://github.com/godotengine/godot-git-plugin/compare/v3.0.0...master

**Comment by ompadu** [comment] 2023-12-02 07:29
4.2 is out, maybe it should be taken into account for the next update

**Comment by juangea** [comment] 2023-12-17 18:46
Can we have a nightly build of the plugin compatible with 4.1 and 4.2 please?

**Comment by Calinou** [comment] 2023-12-17 20:57
> Can we have a nightly build of the plugin compatible with 4.1 and 4.2 please?

https://github.com/godotengine/godot-git-plugin/issues/196#issuecomment-1738091498 should work with both 4.1 and 4.2 as GDExtension API hasn't changed since 4.1.

**Comment by juangea** [comment] 2023-12-17 21:00
Thanks, I missed that comment! :)

**Comment by daveTheOldCoder** [comment] 2023-12-17 22:43
[quote]should work with both 4.1 and 4.2[/quote]

I can confirm that it (3.0.1) does work with both 4.1 and 4.2. It's been almost three months since that was published here. Is there a reason why it's not in the repo and the asset library?

**Comment by Calinou** [comment] 2023-12-18 00:39
> Is there a reason why it's not published as a release here and updated in the asset library?

Lack of time to package it into a release :slightly_smiling_face: 

I've used the `release.sh` script to create a v3.1.0 release, can you test it? https://github.com/godotengine/godot-git-plugin/releases/tag/v3.1.0

**Comment by daveTheOldCoder** [comment] 2023-12-18 01:01
I just did some quick tests using Godot 4.2.1-stable, and it worked correctly.

I'll make a post on the forum asking others to test it.

**Comment by Calinou** [comment] 2023-12-18 13:03
I'll close this as this seems to be resolved now.

**Closed by Calinou** 2023-12-18 13:03 UTC
Labels: bug, confirmed

**Comment by daveTheOldCoder** [comment] 2023-12-19 00:45
> I'll close this as this seems to be resolved now.

There's still the update to the Asset Library, unless it's been submitting and is awaiting approval.
https://godotengine.org/asset-library/asset?filter=godot-git-plugin&category=&godot_version=&cost=&sort=updated

I suppose I could do that, if no want else wants to bother with it.

**Comment by Calinou** [comment] 2023-12-19 14:50
> > I'll close this as this seems to be resolved now.

I've updated the existing 4.0+ asset library submission (doing so requires write access).

**Comment by daveTheOldCoder** [comment] 2023-12-19 15:42
When I first submitted an asset to the library, I specified the latest version of Godot on which I had tested it. I later realized that the specified version should be the lowest that's compatible, since that determines whether it's visible when accessing the asset library from Godot.

**Comment by Calinou** [comment] 2023-12-19 16:21
> I later realized that the specified version should be the lowest that's compatible, since that determines whether it's visible when accessing the asset library from Godot.

You're correct, this appears to already be the case.

**Comment by daveTheOldCoder** [comment] 2023-12-19 17:08
Shouldn't there be separate assets for 4.0 and 4.1/4.2, so that 4.0 users have a compatible plugin to use?
