### ISSUE TITLE
Plugin crashes editor if a staged file has been modified and renamed

### ISSUE THREAD

**Issue by megalobyte** [godotengine/godot-git-plugin#184] opened 2023-05-02 05:28 UTC
Hello, I did some minor problem isolation and I believe that the plugin crashes the editor when a staged file and modified. This seems to line up with the out of range error that I see in the terminal. 

# Workaround: 
Once a file is in this state the editor can not open, so this can not be fixed with the plugin. You need to commit the file to the git repo in order to reopen the project. 

# Error logs:
This is the error log in the terminal:
```
terminate called after throwing an instance of 'std::out_of_range'
  what():  _Map_base::at
fish: Job 1, 'godot --editor' terminated by signal SIGABRT (Abort)
``` 

# Recreate
To recreate this issue, open a file being tracked in git, modify it, rename it, then try to stage the file.

**Comment by emyasnikov** [comment] 2023-05-22 21:53
It definitely crashes and breaks the editor on startup!

**Comment by Inve1951** [comment] 2023-05-23 20:09
Duplicate of #179?

**Comment by Calinou** [comment] 2023-05-23 21:15
- Duplicate of https://github.com/godotengine/godot-git-plugin/issues/179.

**Closed by Calinou** 2023-05-23 21:15 UTC
Labels: bug, confirmed
