### ISSUE TITLE
Plugin import error

### ISSUE THREAD

**Issue by Flash1232** [godotengine/godot-git-plugin#11] opened 2020-01-31 15:14 UTC
I encountered the following error when trying to use the plugin with GodotEngine X11 v3.2-stable on ArchLinux (Linux Kernel v5.4.15):

> E 0:00:00.462   open_dynamic_library: Can't open dynamic library: /home/[username]/Documents/Git/[project_folder]/bin/x11/libgitapi.so. Error: /home/[username]/Documents/Git/[project_folder]/bin/x11/libgitapi.so: undefined symbol: deflateInit_
  <C++ Error>   Condition "!p_library_handle" is true. Returned: ERR_CANT_OPEN
  <C++ Source>  drivers/unix/os_unix.cpp:424 @ open_dynamic_library()

**Comment by IronicallySerious** [comment] 2020-02-01 23:35
This might be happening because of the Libgit2 binaries were built from an Ubuntu 18.10 system. Do you encounter this error with other GDNative plugins too?

**Comment by IronicallySerious** [comment] 2020-02-02 11:14
Might be related to this https://github.com/godotengine/godot/issues/20765

**Comment by arigoru** [comment] 2020-02-02 13:22
Ubuntu 18.04 LTS here, same issue:  
```
ERROR: open_dynamic_library: Can't open dynamic library: /media/[user]/Projects/Godot/[project]/bin/x11/libgitapi.so. Error: /media/[user]/Projects/Godot/[project]/bin/x11/libgitapi.so: undefined symbol: deflateInit_
   At: drivers/unix/os_unix.cpp:424.
ERROR: open_dynamic_library: Can't open dynamic library: /media/[user]/Projects/Godot/[project]/bin/x11/libgitapi.so. Error: /media/[user]/Projects/Godot/[project]/bin/x11/libgitapi.so: undefined symbol: deflateInit_
   At: drivers/unix/os_unix.cpp:424.
ERROR: get_symbol: No valid library handle, can't get symbol from GDNative object
   At: modules/gdnative/gdnative.cpp:483.
ERROR: init_library: No nativescript_init in "res://bin/x11/libgitapi.so" found
   At: modules/gdnative/nativescript/nativescript.cpp:1506.

```

**Comment by arigoru** [comment] 2020-02-03 15:23
Small update on the issue. I have two versions of Godot - normal and C# Mono build, and issue only persists in normal version. Mono build of Godot initializes with no issues.

**Comment by IronicallySerious** [comment] 2020-02-05 12:04
That could indicate a regression. I haven't been able to reproduce this yet though. I will try if mixing release/debug builds or the C# build does anything different

**Comment by IronicallySerious** [comment] 2020-02-14 19:11
Finally reproduced this, but on my Windows system. It believe this is mostly related to mixing release and debug builds. A fix is in the works.

**Comment by IronicallySerious** [comment] 2020-02-14 20:04
I am sure this was an issue of mixing debug and release modes. I segregated the builds properly this time and since I have not been able to reproduce this. 

This will be reflected in the next release. Closing this for now

**Comment by IronicallySerious** [comment] 2020-02-17 06:10
This was found happening in Windows again

**Comment by kforney** [comment] 2020-03-07 02:43
Also occurring on my Arch Linux system:

Godot Engine v3.2.stable.custom_build - https://godotengine.org
OpenGL ES 3.0 Renderer: GeForce GTX 1050 Ti/PCIe/SSE2
 
ERROR: open_dynamic_library: Can't open dynamic library: /data/code/godotengine/godot-git-plugin/demo/bin/x11/release/libgitapi.so. Error: /data/code/godotengine/godot-git-plugin/demo/bin/x11/release/libgitapi.so: undefined symbol: deflateInit_
   At: drivers/unix/os_unix.cpp:424.
ERROR: open_dynamic_library: Can't open dynamic library: /data/code/godotengine/godot-git-plugin/demo/bin/x11/release/libgitapi.so. Error: /data/code/godotengine/godot-git-plugin/demo/bin/x11/release/libgitapi.so: undefined symbol: deflateInit_
   At: drivers/unix/os_unix.cpp:424.
ERROR: get_symbol: No valid library handle, can't get symbol from GDNative object
   At: modules/gdnative/gdnative.cpp:483.
ERROR: init_library: No nativescript_init in "res://bin/x11/release/libgitapi.so" found
   At: modules/gdnative/nativescript/nativescript.cpp:1506.
ERROR: get_symbol: No valid library handle, can't get symbol from GDNative object
   At: modules/gdnative/gdnative.cpp:483.

**Comment by PockelHockel** [comment] 2020-03-07 11:34
Same for me on Ubuntu 19.10...

**Comment by IronicallySerious** [comment] 2020-03-30 09:22
Quoting from [here](https://github.com/godotengine/godot-git-plugin/issues/22)
> Found the issue. Libgit2 has been compiled without the bundled Zlib, which means that it relies on the system to provide a libzlib.so in linux and likewise on other platforms.
Fixing this is merely recompiling libgit2 and flipping the switch: `USE_BUNDLED_ZLIB`

**Comment by IronicallySerious** [comment] 2020-03-30 11:29
Should be fixed on master. Will close with the next release

**Comment by RealTehreal** [comment] 2020-04-07 19:50
Hi there,
I'm on Pop!OS 19.10 and compiled from source because the last release didn't work. Now I get the following errors when godot tries to load the plugin:

`ERROR: open_dynamic_library: Can't open dynamic library: /mnt/ramdisk/Test/bin/x11/release/libgitapi.so. Error: /mnt/ramdisk/Test/bin/x11/release/libgitapi.so: failed to map segment from shared object
   At: drivers/unix/os_unix.cpp:424.
ERROR: get_symbol: No valid library handle, can't get symbol from GDNative object
   At: modules/gdnative/gdnative.cpp:483.
ERROR: init_library: No nativescript_init in "res://bin/x11/release/libgitapi.so" found
   At: modules/gdnative/nativescript/nativescript.cpp:1506.
ERROR: get_symbol: No valid library handle, can't get symbol from GDNative object
   At: modules/gdnative/gdnative.cpp:483.`

Some help would be very appreciated.

Greets

**Comment by IronicallySerious** [comment] 2020-04-07 23:04
What version of Godot are you using?

**Comment by RealTehreal** [comment] 2020-04-08 07:26
Godot_v3.2.1-stable_x11.64

> What version of Godot are you using?

**Comment by IronicallySerious** [comment] 2020-04-10 11:34
I recommend trying with the newer release v1.2: https://github.com/godotengine/godot-git-plugin/releases/tag/v1.2
Feel free to comment here if any issues occur.

**Comment by RealTehreal** [comment] 2020-04-10 13:39
It works now. But the issue was on my side.
First it didn't work, using the latest release. Then after more digging I found out what the issue was:
No exec permissions on the drive with the libgitapi.so
In my case, I was running it on a ramdrive. After remounting with exec permissions 
(`sudo mount -o remount,exec /mnt/ramdisk`)
it worked.
Thanks for enduring me :-)

**Comment by IronicallySerious** [comment] 2020-04-10 14:07
That's good to know. That might have been the issue, however, I fixed some other issues that might get in the way anyway. Closing till newer reports come in.

**Closed by IronicallySerious** 2020-04-10 14:07 UTC
Labels: bug
